version: "3.7"
services:
  blog-mysql:
    image: mysql:5
    container_name: blog-mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: jyDev_01
  blog-web:
    build:
      context: .
      args:
        version: $VERSION
    image: blog-web:$VERSION
    container_name: blog-web
    ports:
    - 8080:8080