spring:
  datasource:
    url: jdbc:mysql://blog-mysql.cno6wo66nmvg.us-east-1.rds.amazonaws.com:3306/blog
    username: admin
    password: jyDev_01
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      use-new-id-generator-mappings: true
    open-in-view: false
server:
  port: 8088