spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: jyDev_01
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      use-new-id-generator-mappings: true
    open-in-view: false
